version: '3.8'
services:
  gameapi:
    image: galaxai-gameapi:local
    build: ./backend
    ports:
      - "5000:80"
  web:
    image: galaxai-web:local
    build: ./web
    ports:
      - "8080:80"
  nanobot:
    image: galaxai-nanobot:local
    build: ./nanobot-skill
    environment:
      - TELEGRAM_TOKEN
      - GALAXAI_API_KEY
